package upmc.train.model.server.ihm;

import javax.swing.JFrame;

public class MonitorLauncherIHM extends JFrame {

	    /**
	 * 
	 */
	private static final long serialVersionUID = -5014334953537994939L;
		public MonitorLauncherIHM() {
	        initComponents();
	    }

	    /**
	     * This method is called from within the constructor to initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is always
	     * regenerated by the Form Editor.
	     */
	    
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	    private void initComponents() {

	        simulationMode = new javax.swing.JCheckBox();
	        jLabel1 = new javax.swing.JLabel();
	        jScrollPane2 = new javax.swing.JScrollPane();
	        monitorMessages = new javax.swing.JTextArea();
	        serverMessages = new javax.swing.JLabel();
	        startStopButton = new javax.swing.JButton();
	        jScrollPane1 = new javax.swing.JScrollPane();
	        connectedControlers = new javax.swing.JList();
	        arduinoUSBPort = new javax.swing.JComboBox();
	        addArduino = new javax.swing.JButton();
	        withrottleAddress = new javax.swing.JTextField();
	        jLabel2 = new javax.swing.JLabel();
	        jLabel3 = new javax.swing.JLabel();
	        wiThrottlePort = new javax.swing.JTextField();

	        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
	        getContentPane().setLayout(null);

	        simulationMode.setText("Simulation Mode");
	        simulationMode.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                simulationModeActionPerformed(evt);
	            }
	        });
	        getContentPane().add(simulationMode);
	        simulationMode.setBounds(0, 130, 160, 23);

	        jLabel1.setText("Connected controler");
	        getContentPane().add(jLabel1);
	        jLabel1.setBounds(10, 160, 160, 16);

	        monitorMessages.setColumns(20);
	        monitorMessages.setRows(5);
	        jScrollPane2.setViewportView(monitorMessages);

	        getContentPane().add(jScrollPane2);
	        jScrollPane2.setBounds(290, 180, 460, 430);

	        serverMessages.setText("Monitor messages");
	        getContentPane().add(serverMessages);
	        serverMessages.setBounds(290, 160, 130, 16);

	        startStopButton.setText("Start");
	        startStopButton.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                startStopButtonActionPerformed(evt);
	            }
	        });
	        getContentPane().add(startStopButton);
	        startStopButton.setBounds(150, 130, 75, 29);

	        jScrollPane1.setViewportView(connectedControlers);

	        getContentPane().add(jScrollPane1);
	        jScrollPane1.setBounds(10, 180, 270, 430);

	        getContentPane().add(arduinoUSBPort);
	        arduinoUSBPort.setBounds(0, 50, 200, 27);

	        addArduino.setText("add arduino");
	        addArduino.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                addArduinoActionPerformed(evt);
	            }
	        });
	        getContentPane().add(addArduino);
	        addArduino.setBounds(200, 50, 190, 29);

	        withrottleAddress.setText("localhost");
	        getContentPane().add(withrottleAddress);
	        withrottleAddress.setBounds(470, 50, 130, 28);

	        jLabel2.setText("Withrottle server");
	        getContentPane().add(jLabel2);
	        jLabel2.setBounds(470, 30, 120, 16);

	        jLabel3.setText("Withrottle port");
	        getContentPane().add(jLabel3);
	        jLabel3.setBounds(630, 30, 110, 16);

	        wiThrottlePort.setText("55555");
	        getContentPane().add(wiThrottlePort);
	        wiThrottlePort.setBounds(630, 50, 84, 28);

	        pack();
	    }// </editor-fold>                        

	    private void simulationModeActionPerformed(java.awt.event.ActionEvent evt) {                                               
	        // TODO add your handling code here:
	    }                                              

	    private void addArduinoActionPerformed(java.awt.event.ActionEvent evt) {                                           
	        // TODO add your handling code here:
	    }                                          

	    private void startStopButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                
	        // TODO add your handling code here:
	    }                                               

	    // Variables declaration - do not modify                     
	    private javax.swing.JButton addArduino;
	    private javax.swing.JComboBox arduinoUSBPort;
	    private javax.swing.JList connectedControlers;
	    private javax.swing.JLabel jLabel1;
	    private javax.swing.JLabel jLabel2;
	    private javax.swing.JLabel jLabel3;
	    private javax.swing.JScrollPane jScrollPane1;
	    private javax.swing.JScrollPane jScrollPane2;
	    private javax.swing.JTextArea monitorMessages;
	    private javax.swing.JLabel serverMessages;
	    private javax.swing.JCheckBox simulationMode;
	    private javax.swing.JButton startStopButton;
	    private javax.swing.JTextField wiThrottlePort;
	    private javax.swing.JTextField withrottleAddress;
	    // End of variables declaration                   
	}
